### ISSUE TITLE
Kumo Station To Report Outdoor Temperature

### ISSUE THREAD

**Issue by brgaulin** [dlarrick/pykumo#16]
For our system, we have a kumo station for oil cutover. When the outdoor temperature drops below say 20F, the outdoor unit shuts off, and when the indoor units need heat they call for aux heat(in our case oil). 

We plan to actually use HA instead of this long term, but had it installed as part of a rebate program and that outdoor sensor would be nice to pull in.

Testing some commands via the js version of the tool, I noticed: `{"c":{"eqc":{}}}` returned a lot of data about the kumo station.

Here is an example payload coming back: https://gist.github.com/brgaulin/d6454f829e4179350674f841d24bfda2

The main thing to note is the `oat` property, which is reporting the outdoor temperature in Celsius. 

When sending this payload: `{"c":{"eqc":{ oat: {}}}}`

I get the following resposne:
```json
{
    "r": {
        "eqc": {
            "oat": 12.4
        }
    }
}
```

Proposal: For Kumo Station units, don't expose a climate object, but instead expose a sensor showing outdoor temperature.

I may try a PR for this soon, mostly wanted to write my notes down before I forget 😄 But very open to feedback.

If curious about the full payload coming back. The station is paired to a single indoor unit per zone(up to 4 zones) for being a thermostat, but any unit on that floor if it calls for heat will trigger the oil override. Our first group is simple with only a single indoor unit. But the second one has 3 units. So for that second zone, if any unit calls for heat, the oil will turn on until the designated primary unit reaches the set temp.

**Comment by dlarrick** [comment]
This is great, nice detective work.

I don't have a lot of time this morning to write a full reply, but what I think should happen is that there should be a different type of object created for the KumoStation (i.e. not a PyKumo object), and it should have methods to access the various attributes that might be useful to someone. Outdoor temperature is a big one, as you said, but at  glance maybe also the topology / zone stuff might be useful to someone. Basically anything in there that someone might have a use case for.

Once pykumo library has such an object type, we can worry about what to do with it on the HA side -- likely create sensor object(s) rather than thermostat objects; might be a good time to think about splitting out the secondary attributes of the normal indoor units into their own first-class sensors too.

**Comment by dlarrick** [comment]
If this is working now please close this issue.

**Comment by dlarrick** [comment]
I think this is working now. Closing.
