### ISSUE TITLE
Number of fan speeds = 4

### ISSUE THREAD

**Issue by thomascantrellsea** [dlarrick/pykumo#41]
I'm getting an error where my unit reports 4 fan speeds, and I hit this error/assertion:
```
        if speeds not in (5, 3):
            _LOGGER.info(
                "Unit reports a different number of fan speeds than "
                "supported, %d != [5|3]. Please report which ones work!",
                self._profile['numberOfFanSpeeds'])
```

I have a unit in one of my rooms which is a MSZ-GL24NA which only has four speeds: Low, Medium, High, Very High (according to the Kumo app labels).

Seems like maybe this logic could be updated to support four fan speeds?

Thanks!

Thomas

![image](https://user-images.githubusercontent.com/74448455/232289205-8c3c2b0c-550c-4aef-a077-9c81f88362ee.png)

**Comment by thomascantrellsea** [comment]
As an aside for my units with 3, the current app labels are: Low, Medium, High (and Auto)

For my units with 5, the current app labels are: Quiet, Low, Medium, High, Very High

**Comment by dlarrick** [comment]
It should be possible to support 4 fan speeds, yes, but I'll need some more information.

Pykumo is using the fan speed names that the indoor unit itself reports via its API, with no translation. Notably, the indoor unit expects these same names back when setting the fan speed. That's why you see the log message -- the software doesn't know what the fan speeds are called (by the unit itself) when there are 4 of them. I think the KumoCloud app *is* using a translation.

Can you do the following: For each of your fan speeds: set the indoor unit to that speed (via KumoCloud app or the remote control) and record what the `get_fan_speed` method of the PyKumo object reports. (Or if you're using HomeAssistant, what's reported as the current fan speed -- the 'fan_mode' attribute).

**Comment by thomascantrellsea** [comment]
Sweet!

Using home-assistant, here are the mappings I see for my 

level : kumo name : home-assist name
level 1 : Low : quiet
level 2: Medium : Low (interesting capitalization, wonder if lower-case would work fine too)
level 3: High : powerful
level 4: Very High : superPowerful

**Comment by dlarrick** [comment]
Haven't forgotten about this, just no spare time recently.
